# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exegesis/proto/x86/cpuid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exegesis/proto/x86/cpuid.proto',
  package='exegesis.x86',
  syntax='proto3',
  serialized_pb=_b('\n\x1e\x65xegesis/proto/x86/cpuid.proto\x12\x0c\x65xegesis.x86\"0\n\x0f\x43puIdInputProto\x12\x0c\n\x04leaf\x18\x01 \x01(\r\x12\x0f\n\x07subleaf\x18\x02 \x01(\r\"F\n\x10\x43puIdOutputProto\x12\x0b\n\x03\x65\x61x\x18\x01 \x01(\r\x12\x0b\n\x03\x65\x62x\x18\x02 \x01(\r\x12\x0b\n\x03\x65\x63x\x18\x03 \x01(\r\x12\x0b\n\x03\x65\x64x\x18\x04 \x01(\r\"o\n\x0f\x43puIdEntryProto\x12,\n\x05input\x18\x01 \x01(\x0b\x32\x1d.exegesis.x86.CpuIdInputProto\x12.\n\x06output\x18\x02 \x01(\x0b\x32\x1e.exegesis.x86.CpuIdOutputProto\"C\n\x11X86CpuIdDumpProto\x12.\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1d.exegesis.x86.CpuIdEntryProtob\x06proto3')
)




_CPUIDINPUTPROTO = _descriptor.Descriptor(
  name='CpuIdInputProto',
  full_name='exegesis.x86.CpuIdInputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='leaf', full_name='exegesis.x86.CpuIdInputProto.leaf', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subleaf', full_name='exegesis.x86.CpuIdInputProto.subleaf', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=96,
)


_CPUIDOUTPUTPROTO = _descriptor.Descriptor(
  name='CpuIdOutputProto',
  full_name='exegesis.x86.CpuIdOutputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eax', full_name='exegesis.x86.CpuIdOutputProto.eax', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ebx', full_name='exegesis.x86.CpuIdOutputProto.ebx', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ecx', full_name='exegesis.x86.CpuIdOutputProto.ecx', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='edx', full_name='exegesis.x86.CpuIdOutputProto.edx', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=168,
)


_CPUIDENTRYPROTO = _descriptor.Descriptor(
  name='CpuIdEntryProto',
  full_name='exegesis.x86.CpuIdEntryProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='exegesis.x86.CpuIdEntryProto.input', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output', full_name='exegesis.x86.CpuIdEntryProto.output', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=281,
)


_X86CPUIDDUMPPROTO = _descriptor.Descriptor(
  name='X86CpuIdDumpProto',
  full_name='exegesis.x86.X86CpuIdDumpProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='exegesis.x86.X86CpuIdDumpProto.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=350,
)

_CPUIDENTRYPROTO.fields_by_name['input'].message_type = _CPUIDINPUTPROTO
_CPUIDENTRYPROTO.fields_by_name['output'].message_type = _CPUIDOUTPUTPROTO
_X86CPUIDDUMPPROTO.fields_by_name['entries'].message_type = _CPUIDENTRYPROTO
DESCRIPTOR.message_types_by_name['CpuIdInputProto'] = _CPUIDINPUTPROTO
DESCRIPTOR.message_types_by_name['CpuIdOutputProto'] = _CPUIDOUTPUTPROTO
DESCRIPTOR.message_types_by_name['CpuIdEntryProto'] = _CPUIDENTRYPROTO
DESCRIPTOR.message_types_by_name['X86CpuIdDumpProto'] = _X86CPUIDDUMPPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CpuIdInputProto = _reflection.GeneratedProtocolMessageType('CpuIdInputProto', (_message.Message,), dict(
  DESCRIPTOR = _CPUIDINPUTPROTO,
  __module__ = 'exegesis.proto.x86.cpuid_pb2'
  # @@protoc_insertion_point(class_scope:exegesis.x86.CpuIdInputProto)
  ))
_sym_db.RegisterMessage(CpuIdInputProto)

CpuIdOutputProto = _reflection.GeneratedProtocolMessageType('CpuIdOutputProto', (_message.Message,), dict(
  DESCRIPTOR = _CPUIDOUTPUTPROTO,
  __module__ = 'exegesis.proto.x86.cpuid_pb2'
  # @@protoc_insertion_point(class_scope:exegesis.x86.CpuIdOutputProto)
  ))
_sym_db.RegisterMessage(CpuIdOutputProto)

CpuIdEntryProto = _reflection.GeneratedProtocolMessageType('CpuIdEntryProto', (_message.Message,), dict(
  DESCRIPTOR = _CPUIDENTRYPROTO,
  __module__ = 'exegesis.proto.x86.cpuid_pb2'
  # @@protoc_insertion_point(class_scope:exegesis.x86.CpuIdEntryProto)
  ))
_sym_db.RegisterMessage(CpuIdEntryProto)

X86CpuIdDumpProto = _reflection.GeneratedProtocolMessageType('X86CpuIdDumpProto', (_message.Message,), dict(
  DESCRIPTOR = _X86CPUIDDUMPPROTO,
  __module__ = 'exegesis.proto.x86.cpuid_pb2'
  # @@protoc_insertion_point(class_scope:exegesis.x86.X86CpuIdDumpProto)
  ))
_sym_db.RegisterMessage(X86CpuIdDumpProto)


# @@protoc_insertion_point(module_scope)
